[package]
name = "c4_backend" 
version.workspace = true # Should inherit from root
edition.workspace = true # Should inherit from root

[lib] 

[dependencies]
axum.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true